### ISSUE TITLE
Selection background on selected line

### ISSUE THREAD

**Issue by MatyCZ** [LucasTempass/FlatOcean#2]
Selection background is almost not visible on selected line.

Example: `<BlockBody>` is selected on line 22

Screen:
![image](https://user-images.githubusercontent.com/318575/91130050-53ec1b80-e6ab-11ea-9190-e4611889407f.png)

**Comment by LucasTempass** [comment]
Thank you for your input, I have to agree with you it would benifit from more contrast. I'll be changing it and releasing a new version within the next few days (JetBrain's approval time). Feel free to leave more feedback or report any issues, I'll gladly analyze them.
