### ISSUE TITLE
Scrollbars are almost invisible

### ISSUE THREAD

**Issue by MatyCZ** [LucasTempass/FlatOcean#3]
It is really hard to quickly find scrollbars.

I have checked option Use contrast scrollbars in Settings, but this option has no effect.

![scrollbars](https://user-images.githubusercontent.com/318575/91270585-266da380-e779-11ea-9a72-1c8a1f69f623.jpg)

**Comment by LucasTempass** [comment]
Have you updated it to 2.2? I don't have this issue. Also which IDE are you using?

**Comment by MatyCZ** [comment]
FlatOcean version is 2.2. I use WebStorm 2020.2.1 and PhpStorm 2020.2.

Scrollbars are much more visible only on mouse scrolling. Can you adjust colors for setting Use contrast scrollbars which solves this problem?

When I tried default Darcula theme, scrollbars are slightly more visible than FlatOcean and option Use contrast scrollbars in settings set scrollbars colors to much brighter in normal state (no scrolling).

**Comment by LucasTempass** [comment]
I will be downloading them and testing them out but I haven't been capable of replicating it yet, my scrollbar's color is much brighter.

**Comment by LucasTempass** [comment]
> FlatOcean version is 2.2. I use WebStorm 2020.2.1 and PhpStorm 2020.2.
> 
> Scrollbars are much more visible only on mouse scrolling. Can you adjust colors for setting Use contrast scrollbars which solves this problem?
> 
> When I tried default Darcula theme, scrollbars are slightly more visible than FlatOcean and option Use contrast scrollbars in settings set scrollbars colors to much brighter in normal state (no scrolling).

I have downloaded them both and I haven't had the same issue, I'm uploading version 2.5 right now when it's approved try updating it. Which OS are you using?

**Comment by MatyCZ** [comment]
So, this is weird if your theme has much brighter scrollbars. On my laptop are scrollbars the same as on the work PC. Both computers use Windows 10.

I tried reset color scheme in  Settings > Editor > Color scheme > Restore defaults for this theme but it is the same.

**Comment by LucasTempass** [comment]
As a precaution I've made it brighter, within the next two days a new update will avaliable.
